// <auto-generated />
using System;
using Cnpj.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cnpj.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cnpj.Business.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("abertura")
                        .HasColumnType("date");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<double>("capital_social")
                        .HasColumnType("float");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("complemento")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("data_situacao")
                        .HasColumnType("date");

                    b.Property<string>("data_situacao_especial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("efr")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("fantasia")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("motivo_situacao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("municipio")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("natureza_juridica")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("porte")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("situacao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("situacao_especial")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("ultima_atualizacao")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
